;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	forward-sexp
	hungry-delete-backward
	hungry-delete-forward
	org-delete-char
	org-force-self-insert
	org-self-insert-command
	org-yank
	sp-delete-char
	sp-forward-slurp-sexp
	sp-kill-word
	))

(setq mc/cmds-to-run-once
      '(
	helm-M-x
	org-cycle
	))
